// =====================================================================
// PERMISSION CONSTANTS — Joy Emmanuel Hospital HMIS
// =====================================================================
// All granular permissions used by the RBAC system.
// =====================================================================

export const PERMISSIONS = {
  // Patient
  PATIENT_VIEW: "patient.view",
  PATIENT_CREATE: "patient.create",
  PATIENT_EDIT: "patient.edit",
  PATIENT_MERGE: "patient.merge",
  PATIENT_EXPORT: "patient.export",
  PATIENT_DELETE: "patient.delete",

  // Clinical
  CLINICAL_VIEW: "clinical.view",
  CLINICAL_CREATE: "clinical.create",
  CLINICAL_EDIT: "clinical.edit",
  CLINICAL_SIGN: "clinical.sign",
  CLINICAL_AMEND: "clinical.amend",

  // Encounter
  ENCOUNTER_VIEW: "encounter.view",
  ENCOUNTER_CREATE: "encounter.create",
  ENCOUNTER_EDIT: "encounter.edit",
  ENCOUNTER_CLOSE: "encounter.close",

  // Appointments
  APPOINTMENT_VIEW: "appointment.view",
  APPOINTMENT_CREATE: "appointment.create",
  APPOINTMENT_RESCHEDULE: "appointment.reschedule",
  APPOINTMENT_CANCEL: "appointment.cancel",

  // Triage / Vitals
  TRIAGE_VIEW: "triage.view",
  TRIAGE_RECORD: "triage.record",
  VITALS_RECORD: "vitals.record",

  // Diagnoses
  DIAGNOSIS_VIEW: "diagnosis.view",
  DIAGNOSIS_CREATE: "diagnosis.create",

  // Lab
  LAB_VIEW: "lab.view",
  LAB_ORDER: "lab.order",
  LAB_COLLECT: "lab.collect",
  LAB_PROCESS: "lab.process",
  LAB_RESULT: "lab.result",
  LAB_VERIFY: "lab.verify",
  LAB_AMEND: "lab.amend",

  // Imaging
  IMAGING_VIEW: "imaging.view",
  IMAGING_ORDER: "imaging.order",
  IMAGING_PERFORM: "imaging.perform",
  IMAGING_REPORT: "imaging.report",
  IMAGING_VERIFY: "imaging.verify",

  // Procedures
  PROCEDURE_VIEW: "procedure.view",
  PROCEDURE_PERFORM: "procedure.perform",

  // Pharmacy
  PHARMACY_PRESCRIBE: "pharmacy.prescribe",
  PHARMACY_DISPENSE: "pharmacy.dispense",
  PHARMACY_VIEW: "pharmacy.view",
  PHARMACY_INVENTORY: "pharmacy.inventory",

  // Admission
  ADMISSION_VIEW: "admission.view",
  ADMISSION_CREATE: "admission.create",
  ADMISSION_TRANSFER: "admission.transfer",
  ADMISSION_DISCHARGE: "admission.discharge",
  BED_MANAGE: "bed.manage",

  // Billing
  BILLING_VIEW: "billing.view",
  BILLING_CREATE: "billing.create",
  BILLING_DISCOUNT: "billing.discount",
  BILLING_REFUND: "billing.refund",
  BILLING_PAYMENT: "billing.payment",
  BILLING_CANCEL: "billing.cancel",

  // Insurance
  INSURANCE_VIEW: "insurance.view",
  INSURANCE_CLAIM: "insurance.claim",
  INSURANCE_VERIFY: "insurance.verify",

  // Inventory
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_RECEIVE: "inventory.receive",
  INVENTORY_ISSUE: "inventory.issue",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  PROCUREMENT_MANAGE: "procurement.manage",

  // Reports
  REPORT_VIEW: "report.view",
  REPORT_EXPORT: "report.export",
  ANALYTICS_VIEW: "analytics.view",

  // Users / Roles / Permissions
  USER_CREATE: "user.create",
  USER_EDIT: "user.edit",
  USER_DISABLE: "user.disable",
  USER_VIEW: "user.view",
  ROLE_CREATE: "role.create",
  ROLE_EDIT: "role.edit",
  ROLE_VIEW: "role.view",
  PERMISSION_ASSIGN: "permission.assign",

  // Facility / Department
  FACILITY_MANAGE: "facility.manage",
  DEPARTMENT_MANAGE: "department.manage",

  // Staff
  STAFF_VIEW: "staff.view",
  STAFF_MANAGE: "staff.manage",
  SHIFT_MANAGE: "shift.manage",

  // Audit / Security
  AUDIT_VIEW: "audit.view",
  AUDIT_EXPORT: "audit.export",
  BREAK_GLASS: "break_glass.use",
  SECURITY_DASHBOARD: "security.dashboard",
  DATA_EXPORT: "data.export",

  // System Settings
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_VIEW: "settings.view",

  // Notifications / Tasks
  TASK_ASSIGN: "task.assign",
  TASK_COMPLETE: "task.complete",

  // Documents
  DOCUMENT_UPLOAD: "document.upload",
  DOCUMENT_VIEW: "document.view",
  DOCUMENT_DELETE: "document.delete",

  // Maternity
  MATERNITY_VIEW: "maternity.view",
  MATERNITY_MANAGE: "maternity.manage",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// =====================================================================
// ROLE -> PERMISSION MAPPING (default system roles)
// =====================================================================

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const CLINICAL_FULL = [
  PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_EDIT,
  PERMISSIONS.CLINICAL_VIEW, PERMISSIONS.CLINICAL_CREATE, PERMISSIONS.CLINICAL_EDIT,
  PERMISSIONS.ENCOUNTER_VIEW, PERMISSIONS.ENCOUNTER_CREATE, PERMISSIONS.ENCOUNTER_EDIT, PERMISSIONS.ENCOUNTER_CLOSE,
  PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_RESCHEDULE, PERMISSIONS.APPOINTMENT_CANCEL,
  PERMISSIONS.TRIAGE_VIEW,
  PERMISSIONS.DIAGNOSIS_VIEW, PERMISSIONS.DIAGNOSIS_CREATE,
  PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_ORDER,
  PERMISSIONS.IMAGING_VIEW, PERMISSIONS.IMAGING_ORDER,
  PERMISSIONS.PROCEDURE_VIEW,
  PERMISSIONS.PHARMACY_VIEW, PERMISSIONS.PHARMACY_PRESCRIBE,
  PERMISSIONS.ADMISSION_VIEW, PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
];

// CLINICAL_VIEW_ONLY — for nurses and other clinical support staff who can VIEW
// clinical data and create nursing notes/triage, but CANNOT create consultations
// or sign clinical notes (only doctors/specialists/medical officers can).
const CLINICAL_VIEW_ONLY = CLINICAL_FULL.filter(
  (p) => p !== PERMISSIONS.CLINICAL_CREATE
);

export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  super_admin: ALL_PERMISSIONS,

  organization_admin: [
    ...CLINICAL_FULL,
    PERMISSIONS.PATIENT_MERGE, PERMISSIONS.PATIENT_EXPORT, PERMISSIONS.PATIENT_DELETE,
    PERMISSIONS.CLINICAL_SIGN, PERMISSIONS.CLINICAL_AMEND,
    PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.LAB_COLLECT, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RESULT, PERMISSIONS.LAB_VERIFY, PERMISSIONS.LAB_AMEND,
    PERMISSIONS.IMAGING_PERFORM, PERMISSIONS.IMAGING_REPORT, PERMISSIONS.IMAGING_VERIFY,
    PERMISSIONS.PROCEDURE_PERFORM,
    PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_INVENTORY,
    PERMISSIONS.ADMISSION_CREATE, PERMISSIONS.ADMISSION_TRANSFER, PERMISSIONS.ADMISSION_DISCHARGE, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_DISCOUNT, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_REFUND, PERMISSIONS.BILLING_CANCEL,
    PERMISSIONS.INSURANCE_VIEW, PERMISSIONS.INSURANCE_CLAIM, PERMISSIONS.INSURANCE_VERIFY,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_RECEIVE, PERMISSIONS.INVENTORY_ISSUE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.REPORT_EXPORT, PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.USER_CREATE, PERMISSIONS.USER_EDIT, PERMISSIONS.USER_DISABLE, PERMISSIONS.USER_VIEW,
    PERMISSIONS.ROLE_CREATE, PERMISSIONS.ROLE_EDIT, PERMISSIONS.ROLE_VIEW, PERMISSIONS.PERMISSION_ASSIGN,
    PERMISSIONS.FACILITY_MANAGE, PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE, PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.AUDIT_VIEW, PERMISSIONS.AUDIT_EXPORT, PERMISSIONS.SECURITY_DASHBOARD, PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.SETTINGS_MANAGE, PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.MATERNITY_VIEW, PERMISSIONS.MATERNITY_MANAGE,
    PERMISSIONS.BREAK_GLASS,
  ],

  facility_admin: [
    ...CLINICAL_FULL,
    PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.LAB_COLLECT, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RESULT, PERMISSIONS.LAB_VERIFY,
    PERMISSIONS.IMAGING_PERFORM, PERMISSIONS.IMAGING_REPORT,
    PERMISSIONS.PROCEDURE_PERFORM,
    PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_INVENTORY,
    PERMISSIONS.ADMISSION_CREATE, PERMISSIONS.ADMISSION_TRANSFER, PERMISSIONS.ADMISSION_DISCHARGE, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_DISCOUNT,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_RECEIVE, PERMISSIONS.INVENTORY_ISSUE,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_EDIT,
    PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE, PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.MATERNITY_VIEW, PERMISSIONS.MATERNITY_MANAGE,
    PERMISSIONS.BREAK_GLASS,
  ],

  doctor: [
    ...CLINICAL_FULL,
    PERMISSIONS.CLINICAL_SIGN, PERMISSIONS.CLINICAL_AMEND,
    PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.PROCEDURE_PERFORM,
    PERMISSIONS.ADMISSION_CREATE, PERMISSIONS.ADMISSION_TRANSFER, PERMISSIONS.ADMISSION_DISCHARGE, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.MATERNITY_VIEW, PERMISSIONS.MATERNITY_MANAGE,
    PERMISSIONS.BREAK_GLASS,
  ],

  nurse: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW, PERMISSIONS.CLINICAL_EDIT,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.TRIAGE_VIEW, PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_COLLECT,
    PERMISSIONS.PHARMACY_VIEW,
    PERMISSIONS.ADMISSION_VIEW, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.PROCEDURE_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
  ],

  pharmacist: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.PHARMACY_VIEW, PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_INVENTORY,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ISSUE, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
  ],

  laboratory_scientist: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_COLLECT, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RESULT, PERMISSIONS.LAB_VERIFY, PERMISSIONS.LAB_AMEND,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
  ],

  radiographer: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.IMAGING_VIEW, PERMISSIONS.IMAGING_PERFORM, PERMISSIONS.IMAGING_REPORT,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
  ],

  receptionist: [
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_EDIT,
    PERMISSIONS.ENCOUNTER_VIEW, PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_RESCHEDULE, PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.TRIAGE_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],

  cashier: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_CANCEL,
    PERMISSIONS.INSURANCE_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],

  accountant: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_DISCOUNT, PERMISSIONS.BILLING_REFUND, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_CANCEL,
    PERMISSIONS.INSURANCE_VIEW, PERMISSIONS.INSURANCE_CLAIM,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT, PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],

  records_officer: [
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_EDIT, PERMISSIONS.PATIENT_MERGE, PERMISSIONS.PATIENT_EXPORT,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW, PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.INSURANCE_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],

  inventory_officer: [
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_RECEIVE, PERMISSIONS.INVENTORY_ISSUE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],
};

// Module catalog used by the UI to filter the sidebar by role
export const ROLE_LABELS: Record<string, string> = {
  super_admin: "Super Administrator",
  organization_admin: "Organization Administrator",
  facility_admin: "Facility Administrator",
  doctor: "Doctor / Medical Officer",
  nurse: "Nurse",
  pharmacist: "Pharmacist",
  laboratory_scientist: "Laboratory Scientist",
  radiographer: "Radiographer",
  receptionist: "Receptionist",
  cashier: "Cashier",
  accountant: "Accountant",
  records_officer: "Records Officer",
  inventory_officer: "Inventory Officer",
};
