"use client";

import { ReactNode } from "react";
import { ShieldPlus, Phone, Mail, MapPin } from "lucide-react";

// ─── Hospital branding header ───────────────────────────────────
function HospitalHeader({ facility }: { facility?: any }) {
  const name = facility?.name || "Joy Emmanuel Hospital";
  const address = facility?.address || "Accra, Ghana";
  const phone = facility?.phone || "+233 30 000 0000";
  const email = facility?.email || "info@joyemmanuelhospital.org";

  return (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "2px solid #059669", paddingBottom: "16px", marginBottom: "24px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
        <div style={{ width: "56px", height: "56px", background: "linear-gradient(135deg, #059669, #0d9488)", borderRadius: "12px", display: "flex", alignItems: "center", justifyContent: "center", color: "white", flexShrink: 0 }}>
          <ShieldPlus size={28} />
        </div>
        <div>
          <h1 style={{ fontSize: "18px", fontWeight: 700, color: "#0f172a", margin: 0 }}>{name}</h1>
          <div style={{ fontSize: "10px", color: "#64748b", display: "flex", gap: "12px", marginTop: "2px" }}>
            <span style={{ display: "flex", alignItems: "center", gap: "4px" }}><MapPin size={10} />{address}</span>
            <span style={{ display: "flex", alignItems: "center", gap: "4px" }}><Phone size={10} />{phone}</span>
            <span style={{ display: "flex", alignItems: "center", gap: "4px" }}><Mail size={10} />{email}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Footer with signature line ─────────────────────────────────
function DocumentFooter({ signatory, signatoryRole, facility }: { signatory?: string; signatoryRole?: string; facility?: any }) {
  return (
    <div style={{ marginTop: "48px", paddingTop: "24px", borderTop: "1px solid #e2e8f0" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end" }}>
        <div style={{ fontSize: "10px", color: "#94a3b8" }}>
          <p>Generated by Joy Emmanuel Hospital HMIS on {new Date().toLocaleString("en-GB")}</p>
          {facility && <p>{facility.name} • {facility.address || ""}</p>}
        </div>
        {signatory && (
          <div style={{ textAlign: "center" }}>
            <div style={{ width: "200px", borderBottom: "1px dashed #94a3b8", marginBottom: "4px" }}></div>
            <div style={{ fontSize: "12px", fontWeight: 500, color: "#334155" }}>{signatory}</div>
            {signatoryRole && <div style={{ fontSize: "10px", color: "#64748b" }}>{signatoryRole}</div>}
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Info row ───────────────────────────────────────────────────
function InfoRow({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div style={{ display: "flex", marginBottom: "4px" }}>
      <span style={{ fontSize: "11px", fontWeight: 500, color: "#64748b", width: "120px", flexShrink: 0 }}>{label}:</span>
      <span style={{ fontSize: "11px", color: "#0f172a", fontWeight: 500, flex: 1 }}>{value || "—"}</span>
    </div>
  );
}

// ─── Main PrintLayout ───────────────────────────────────────────
export function PrintLayout({
  title,
  subtitle,
  facility,
  patient,
  documentNumber,
  children,
  signatory,
  signatoryRole,
}: {
  title: string;
  subtitle?: string;
  facility?: any;
  patient?: any;
  documentNumber?: string;
  children: ReactNode;
  signatory?: string;
  signatoryRole?: string;
}) {
  return (
    <div style={{ background: "white", color: "#0f172a", fontFamily: "system-ui, -apple-system, sans-serif", padding: "20px" }}>
      <HospitalHeader facility={facility} />

      {/* Document title */}
      <div style={{ textAlign: "center", marginBottom: "24px" }}>
        <h2 style={{ fontSize: "16px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "#0f172a", margin: 0 }}>{title}</h2>
        {subtitle && <p style={{ fontSize: "11px", color: "#64748b", marginTop: "2px" }}>{subtitle}</p>}
        {documentNumber && (
          <div style={{ display: "inline-block", marginTop: "8px", padding: "2px 12px", background: "#f1f5f9", borderRadius: "4px", fontSize: "11px", fontFamily: "monospace", color: "#475569" }}>
            {documentNumber}
          </div>
        )}
      </div>

      {/* Patient info bar */}
      {patient && (
        <div style={{ background: "#f8fafc", borderRadius: "8px", padding: "12px", marginBottom: "16px", border: "1px solid #e2e8f0", display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "4px 16px" }}>
          <InfoRow label="Patient Name" value={`${patient.firstName || ""} ${patient.lastName || ""}`} />
          <InfoRow label="Patient ID" value={patient.patientNumber} />
          <InfoRow label="Age" value={patient.dateOfBirth ? `${new Date().getFullYear() - new Date(patient.dateOfBirth).getFullYear()} years` : "—"} />
          <InfoRow label="Sex" value={patient.sex} />
          <InfoRow label="Phone" value={patient.phone} />
          <InfoRow label="Blood Group" value={patient.bloodGroup} />
        </div>
      )}

      {/* Document body */}
      <div style={{ minHeight: "200px" }}>{children}</div>

      <DocumentFooter signatory={signatory} signatoryRole={signatoryRole} facility={facility} />
    </div>
  );
}

// ─── Print button ───────────────────────────────────────────────
export function PrintButton({
  label = "Print",
  className = "",
  renderContent,
}: {
  label?: string;
  className?: string;
  renderContent: () => ReactNode;
}) {
  const handlePrint = async () => {
    const content = renderContent();
    const printWindow = window.open("", "_blank", "width=800,height=900");
    if (!printWindow) {
      alert("Please allow popups to print this document.");
      return;
    }

    const ReactDOMServer = await import("react-dom/server");
    const html = ReactDOMServer.renderToStaticMarkup(content);

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${label} — Joy Emmanuel Hospital</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: system-ui, -apple-system, sans-serif; color: #0f172a; padding: 20px; }
          @page { size: A4; margin: 12mm; }
          @media print { body { padding: 0; } .no-print { display: none !important; } }
        </style>
      </head>
      <body>
        ${html}
        <div class="no-print" style="position:fixed;bottom:20px;left:0;right:0;text-align:center;">
          <button onclick="window.print()" style="background:#059669;color:white;border:none;padding:10px 24px;border-radius:8px;font-size:14px;cursor:pointer;">Print Document</button>
        </div>
        <script>setTimeout(function(){window.print();},500);</script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <button
      onClick={handlePrint}
      className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium border border-slate-200 hover:border-emerald-300 hover:bg-emerald-50 transition ${className}`}
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <polyline points="6 9 6 2 18 2 18 9"/>
        <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/>
        <rect x="6" y="14" width="12" height="8"/>
      </svg>
      {label}
    </button>
  );
}
