// =====================================================================
// MODULE CONFIGURATIONS for all extended modules
// =====================================================================
import {
  Droplet, Syringe, Stethoscope, HeartPulse, Bone, Eye, Brain, Ear, Activity,
  Baby, Pill, Beaker, Microscope, ScanLine, Truck, Sparkles, Brush, Shield,
  Ambulance, UtensilsCrossed, Trash2, MessageSquare, ClipboardCheck,
  AlertTriangle, Scale, FlaskRound, Megaphone, Server, FileText, Users,
  Home, FileSearch, BedDouble, ScrollText,
} from "lucide-react";
import type { ModuleConfig } from "./_generic-module-view";

// Reusable status options
const ACTIVE_STATUSES = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
];
const PRIORITY_OPTIONS = [
  { value: "routine", label: "Routine" },
  { value: "urgent", label: "Urgent" },
  { value: "emergency", label: "Emergency" },
];
const SEVERITY_OPTIONS = [
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
  { value: "critical", label: "Critical" },
];
const OPEN_CLOSED = [
  { value: "open", label: "Open" },
  { value: "in_progress", label: "In Progress" },
  { value: "resolved", label: "Resolved" },
  { value: "closed", label: "Closed" },
];

// =====================================================================
// BLOOD BANK - DONORS
// =====================================================================
export const BLOOD_DONOR_CONFIG: ModuleConfig = {
  viewKey: "blood_donors",
  title: "Blood Donors",
  description: "Register and manage blood donors, track eligibility and donation history.",
  icon: HeartPulse,
  apiPath: "blood-bank/donors",
  queryKey: "blood-donors",
  viewPermission: "bloodbank.view",
  managePermission: "bloodbank.manage",
  numberField: "donorNumber",
  searchFields: ["fullName", "donorNumber", "phone", "bloodGroup"],
  filters: [
    { param: "bloodGroup", label: "Blood Group", options: [
      { value: "A+", label: "A+" }, { value: "A-", label: "A-" },
      { value: "B+", label: "B+" }, { value: "B-", label: "B-" },
      { value: "AB+", label: "AB+" }, { value: "AB-", label: "AB-" },
      { value: "O+", label: "O+" }, { value: "O-", label: "O-" },
    ]},
    { param: "eligibilityStatus", label: "Eligibility", options: [
      { value: "eligible", label: "Eligible" },
      { value: "deferred", label: "Deferred" },
      { value: "banned", label: "Banned" },
    ]},
  ],
  fields: [
    { name: "fullName", label: "Full Name", type: "text", required: true },
    { name: "age", label: "Age", type: "number" },
    { name: "sex", label: "Sex", type: "select", options: [
      { value: "male", label: "Male" }, { value: "female", label: "Female" },
    ]},
    { name: "bloodGroup", label: "Blood Group", type: "select", options: [
      { value: "A+", label: "A+" }, { value: "A-", label: "A-" },
      { value: "B+", label: "B+" }, { value: "B-", label: "B-" },
      { value: "AB+", label: "AB+" }, { value: "AB-", label: "AB-" },
      { value: "O+", label: "O+" }, { value: "O-", label: "O-" },
    ]},
    { name: "rhFactor", label: "Rh Factor", type: "select", options: [
      { value: "+", label: "Positive" }, { value: "-", label: "Negative" },
    ]},
    { name: "phone", label: "Phone", type: "text" },
    { name: "email", label: "Email", type: "text" },
    { name: "address", label: "Address", type: "textarea", full: true },
    { name: "occupation", label: "Occupation", type: "text" },
    { name: "donorType", label: "Donor Type", type: "select", options: [
      { value: "voluntary", label: "Voluntary" },
      { value: "replacement", label: "Replacement" },
      { value: "autologous", label: "Autologous" },
      { value: "directed", label: "Directed" },
    ]},
    { name: "eligibilityStatus", label: "Eligibility", type: "select", options: [
      { value: "eligible", label: "Eligible" },
      { value: "deferred", label: "Deferred" },
      { value: "banned", label: "Banned" },
    ]},
    { name: "deferralReason", label: "Deferral Reason", type: "text", hideInList: true },
    { name: "deferralUntil", label: "Deferral Until", type: "date", hideInList: true },
    { name: "hbsAg", label: "HBsAg", type: "text", hideInList: true },
    { name: "hcvAb", label: "HCV Ab", type: "text", hideInList: true },
    { name: "hivAb", label: "HIV Ab", type: "text", hideInList: true },
    { name: "syphilis", label: "Syphilis", type: "text", hideInList: true },
    { name: "notes", label: "Notes", type: "textarea", full: true, hideInList: true },
  ],
  auditActionCreate: "BLOOD_DONOR_CREATED",
  auditActionUpdate: "BLOOD_DONOR_UPDATED",
  accentColor: "text-rose-600",
};

// =====================================================================
// BLOOD BANK - UNITS
// =====================================================================
export const BLOOD_UNIT_CONFIG: ModuleConfig = {
  viewKey: "blood_units",
  title: "Blood Units Inventory",
  description: "Track collected blood units, storage, expiry, and issue to patients.",
  icon: Droplet,
  apiPath: "blood-bank/units",
  queryKey: "blood-units",
  viewPermission: "bloodbank.view",
  managePermission: "bloodbank.manage",
  numberField: "unitNumber",
  searchFields: ["unitNumber", "bloodGroup"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "available", label: "Available" },
      { value: "reserved", label: "Reserved" },
      { value: "issued", label: "Issued" },
      { value: "transfused", label: "Transfused" },
      { value: "expired", label: "Expired" },
      { value: "discarded", label: "Discarded" },
    ]},
    { param: "bloodGroup", label: "Blood Group", options: [
      { value: "A+", label: "A+" }, { value: "A-", label: "A-" },
      { value: "B+", label: "B+" }, { value: "B-", label: "B-" },
      { value: "AB+", label: "AB+" }, { value: "AB-", label: "AB-" },
      { value: "O+", label: "O+" }, { value: "O-", label: "O-" },
    ]},
    { param: "componentType", label: "Component", options: [
      { value: "whole_blood", label: "Whole Blood" },
      { value: "prbc", label: "PRBC" },
      { value: "ffp", label: "FFP" },
      { value: "platelets", label: "Platelets" },
      { value: "cryo", label: "Cryoprecipitate" },
    ]},
  ],
  fields: [
    { name: "donorId", label: "Donor ID", type: "text", required: true, placeholder: "Donor ID from donor registry" },
    { name: "bloodGroup", label: "Blood Group", type: "select", required: true, options: [
      { value: "A+", label: "A+" }, { value: "A-", label: "A-" },
      { value: "B+", label: "B+" }, { value: "B-", label: "B-" },
      { value: "AB+", label: "AB+" }, { value: "AB-", label: "AB-" },
      { value: "O+", label: "O+" }, { value: "O-", label: "O-" },
    ]},
    { name: "componentType", label: "Component Type", type: "select", options: [
      { value: "whole_blood", label: "Whole Blood" },
      { value: "prbc", label: "PRBC" },
      { value: "ffp", label: "FFP" },
      { value: "platelets", label: "Platelets" },
      { value: "cryo", label: "Cryoprecipitate" },
    ]},
    { name: "volumeMl", label: "Volume (ml)", type: "number" },
    { name: "collectionDate", label: "Collection Date", type: "datetime-local" },
    { name: "expiryDate", label: "Expiry Date", type: "datetime-local", required: true },
    { name: "storageTemp", label: "Storage Temperature", type: "text", placeholder: "e.g. 2-6°C" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "available", label: "Available" },
      { value: "reserved", label: "Reserved" },
      { value: "issued", label: "Issued" },
      { value: "transfused", label: "Transfused" },
      { value: "expired", label: "Expired" },
      { value: "discarded", label: "Discarded" },
    ]},
    { name: "reservedForPatientId", label: "Reserved For Patient ID", type: "text", hideInList: true },
    { name: "reservedForPatientName", label: "Reserved For Patient Name", type: "text", hideInList: true },
    { name: "reservedUntil", label: "Reserved Until", type: "datetime-local", hideInList: true },
    { name: "issuedToPatientId", label: "Issued To Patient ID", type: "text", hideInList: true },
    { name: "issuedToPatientName", label: "Issued To Patient Name", type: "text", hideInList: true },
    { name: "notes", label: "Notes", type: "textarea", full: true, hideInList: true },
  ],
  auditActionCreate: "BLOOD_UNIT_CREATED",
  auditActionUpdate: "BLOOD_UNIT_UPDATED",
  accentColor: "text-rose-600",
};

// =====================================================================
// BLOOD BANK - TRANSFUSIONS
// =====================================================================
export const BLOOD_TRANSFUSION_CONFIG: ModuleConfig = {
  viewKey: "blood_transfusions",
  title: "Blood Transfusions",
  description: "Record blood transfusions administered to patients with reaction monitoring.",
  icon: Syringe,
  apiPath: "blood-bank/transfusions",
  queryKey: "blood-transfusions",
  viewPermission: "bloodbank.view",
  managePermission: "bloodbank.transfuse",
  numberField: "transfusionNumber",
  searchFields: ["transfusionNumber", "patientName"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "aborted", label: "Aborted" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientBloodGroup", label: "Patient Blood Group", type: "select", options: [
      { value: "A+", label: "A+" }, { value: "A-", label: "A-" },
      { value: "B+", label: "B+" }, { value: "B-", label: "B-" },
      { value: "AB+", label: "AB+" }, { value: "AB-", label: "AB-" },
      { value: "O+", label: "O+" }, { value: "O-", label: "O-" },
    ]},
    { name: "unitId", label: "Blood Unit ID", type: "text", required: true },
    { name: "unitNumber", label: "Unit Number", type: "text", hideInForm: true },
    { name: "bloodGroup", label: "Unit Blood Group", type: "text", hideInForm: true },
    { name: "componentType", label: "Component Type", type: "text", hideInForm: true },
    { name: "volumeMl", label: "Volume (ml)", type: "number", hideInForm: true },
    { name: "preTransfusionVitals", label: "Pre-Transfusion Vitals (JSON)", type: "textarea", full: true },
    { name: "postTransfusionVitals", label: "Post-Transfusion Vitals (JSON)", type: "textarea", full: true },
    { name: "reactionObserved", label: "Reaction Observed", type: "checkbox" },
    { name: "reactionDetails", label: "Reaction Details", type: "textarea", full: true },
    { name: "startedAt", label: "Started At", type: "datetime-local" },
    { name: "completedAt", label: "Completed At", type: "datetime-local" },
    { name: "administeredById", label: "Administered By ID", type: "text" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "aborted", label: "Aborted" },
    ]},
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "BLOOD_TRANSFUSION_STARTED",
  auditActionUpdate: "BLOOD_TRANSFUSION_UPDATED",
  accentColor: "text-rose-600",
};

// =====================================================================
// OPERATING THEATRE
// =====================================================================
export const THEATRE_CONFIG: ModuleConfig = {
  viewKey: "theatre",
  title: "Operating Theatre",
  description: "Schedule surgical cases, track procedures, anaesthesia, and outcomes.",
  icon: Stethoscope,
  apiPath: "theatre",
  queryKey: "theatre-cases",
  viewPermission: "theatre.view",
  managePermission: "theatre.manage",
  numberField: "caseNumber",
  searchFields: ["caseNumber", "patientName", "procedureName", "surgeonName"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "scheduled", label: "Scheduled" },
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
      { value: "delayed", label: "Delayed" },
    ]},
    { param: "procedureType", label: "Type", options: [
      { value: "elective", label: "Elective" },
      { value: "emergency", label: "Emergency" },
      { value: "urgent", label: "Urgent" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientAge", label: "Patient Age", type: "number" },
    { name: "patientSex", label: "Patient Sex", type: "select", options: [
      { value: "male", label: "Male" }, { value: "female", label: "Female" },
    ]},
    { name: "encounterId", label: "Encounter ID", type: "text" },
    { name: "admissionId", label: "Admission ID", type: "text" },
    { name: "procedureType", label: "Procedure Type", type: "select", options: [
      { value: "elective", label: "Elective" },
      { value: "emergency", label: "Emergency" },
      { value: "urgent", label: "Urgent" },
    ]},
    { name: "procedureName", label: "Procedure Name", type: "text", required: true },
    { name: "procedureCode", label: "Procedure Code (CPT/ICD-9-PCS)", type: "text" },
    { name: "surgeonName", label: "Surgeon", type: "text" },
    { name: "surgeonId", label: "Surgeon ID", type: "text" },
    { name: "anesthetistName", label: "Anesthetist", type: "text" },
    { name: "anesthetistId", label: "Anesthetist ID", type: "text" },
    { name: "scrubNurseName", label: "Scrub Nurse", type: "text" },
    { name: "scrubNurseId", label: "Scrub Nurse ID", type: "text" },
    { name: "theatreRoom", label: "Theatre Room", type: "text" },
    { name: "scheduledStart", label: "Scheduled Start", type: "datetime-local", required: true },
    { name: "scheduledEnd", label: "Scheduled End", type: "datetime-local" },
    { name: "actualStart", label: "Actual Start", type: "datetime-local" },
    { name: "actualEnd", label: "Actual End", type: "datetime-local" },
    { name: "anesthesiaType", label: "Anesthesia Type", type: "select", options: [
      { value: "general", label: "General" },
      { value: "regional", label: "Regional" },
      { value: "local", label: "Local" },
      { value: "spinal", label: "Spinal" },
      { value: "epidural", label: "Epidural" },
      { value: "sedation", label: "Sedation" },
    ]},
    { name: "preOpDiagnosis", label: "Pre-op Diagnosis", type: "textarea", full: true },
    { name: "postOpDiagnosis", label: "Post-op Diagnosis", type: "textarea", full: true },
    { name: "findings", label: "Findings", type: "textarea", full: true },
    { name: "procedureNotes", label: "Procedure Notes", type: "textarea", full: true },
    { name: "complications", label: "Complications", type: "textarea", full: true },
    { name: "bloodLossMl", label: "Blood Loss (ml)", type: "number" },
    { name: "specimensSent", label: "Specimens Sent", type: "text" },
    { name: "implantUsed", label: "Implant Used", type: "text" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "scheduled", label: "Scheduled" },
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
      { value: "delayed", label: "Delayed" },
    ]},
    { name: "recoveryStatus", label: "Recovery Status", type: "select", options: [
      { value: "recovering", label: "Recovering" },
      { value: "recovered_to_ward", label: "Recovered to Ward" },
      { value: "icu_transfer", label: "ICU Transfer" },
    ]},
  ],
  auditActionCreate: "THEATRE_CASE_SCHEDULED",
  auditActionUpdate: "THEATRE_CASE_UPDATED",
  accentColor: "text-blue-600",
};

// =====================================================================
// CRITICAL CARE (ICU/NICU)
// =====================================================================
export const CRITICAL_CARE_CONFIG: ModuleConfig = {
  viewKey: "critical_care",
  title: "Critical Care (ICU / NICU)",
  description: "Manage critical care admissions, monitoring, ventilator support, and outcomes.",
  icon: Activity,
  apiPath: "critical-care",
  queryKey: "critical-care",
  viewPermission: "critical_care.view",
  managePermission: "critical_care.manage",
  numberField: "admissionNumber",
  searchFields: ["admissionNumber", "patientName", "admittingDiagnosis"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "admitted", label: "Admitted" },
      { value: "discharged", label: "Discharged" },
      { value: "deceased", label: "Deceased" },
    ]},
    { param: "unitType", label: "Unit", options: [
      { value: "icu", label: "ICU" },
      { value: "nicu", label: "NICU" },
      { value: "picu", label: "PICU" },
      { value: "ccu", label: "CCU" },
      { value: "hdu", label: "HDU" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientAge", label: "Patient Age", type: "number" },
    { name: "patientSex", label: "Patient Sex", type: "select", options: [
      { value: "male", label: "Male" }, { value: "female", label: "Female" },
    ]},
    { name: "encounterId", label: "Encounter ID", type: "text" },
    { name: "admissionId", label: "Admission ID", type: "text" },
    { name: "unitType", label: "Unit Type", type: "select", required: true, options: [
      { value: "icu", label: "ICU" },
      { value: "nicu", label: "NICU" },
      { value: "picu", label: "PICU" },
      { value: "ccu", label: "CCU" },
      { value: "hdu", label: "HDU" },
    ]},
    { name: "bedNumber", label: "Bed Number", type: "text" },
    { name: "admittingDiagnosis", label: "Admitting Diagnosis", type: "text", required: true, full: true },
    { name: "admissionReason", label: "Admission Reason", type: "textarea", full: true },
    { name: "severity", label: "Severity", type: "select", options: [
      { value: "critical", label: "Critical" },
      { value: "serious", label: "Serious" },
      { value: "stable", label: "Stable" },
    ]},
    { name: "apacheScore", label: "APACHE II Score", type: "number" },
    { name: "attendingPhysicianName", label: "Attending Physician", type: "text" },
    { name: "attendingPhysicianId", label: "Attending Physician ID", type: "text" },
    { name: "ventilator", label: "On Ventilator", type: "checkbox" },
    { name: "ventilatorSettings", label: "Ventilator Settings (JSON)", type: "textarea", full: true },
    { name: "dialysis", label: "On Dialysis", type: "checkbox" },
    { name: "inotropes", label: "Inotropes", type: "text" },
    { name: "monitoringData", label: "Monitoring Data (JSON)", type: "textarea", full: true },
    { name: "status", label: "Status", type: "select", options: [
      { value: "admitted", label: "Admitted" },
      { value: "discharged", label: "Discharged" },
      { value: "deceased", label: "Deceased" },
    ]},
    { name: "dischargedAt", label: "Discharged At", type: "datetime-local" },
    { name: "dischargeDestination", label: "Discharge Destination", type: "select", options: [
      { value: "ward", label: "Ward" },
      { value: "home", label: "Home" },
      { value: "morgue", label: "Morgue" },
      { value: "transfer_out", label: "Transfer Out" },
    ]},
    { name: "outcomeNotes", label: "Outcome Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "CRITICAL_CARE_ADMISSION",
  auditActionUpdate: "CRITICAL_CARE_UPDATED",
  accentColor: "text-rose-600",
};

// =====================================================================
// SPECIALTY CLINICS
// =====================================================================
export const SPECIALTY_CONFIG: ModuleConfig = {
  viewKey: "specialty",
  title: "Specialty Clinics",
  description: "Dental, Eye, ENT, Physiotherapy, Psychiatry, Dermatology, Cardiology, Neurology, Orthopaedics, Urology.",
  icon: Stethoscope,
  apiPath: "specialty",
  queryKey: "specialty-encounters",
  viewPermission: "specialty.view",
  managePermission: "specialty.manage",
  numberField: "encounterNumber",
  searchFields: ["encounterNumber", "patientName", "chiefComplaint", "diagnosis"],
  filters: [
    { param: "departmentCode", label: "Specialty", options: [
      { value: "DENTAL", label: "Dental" },
      { value: "OPHTH", label: "Ophthalmology" },
      { value: "ENT", label: "ENT" },
      { value: "PHYSIO", label: "Physiotherapy" },
      { value: "PSYCH", label: "Psychiatry" },
      { value: "DERM", label: "Dermatology" },
      { value: "CARDIO", label: "Cardiology" },
      { value: "NEURO", label: "Neurology" },
      { value: "ORTHO", label: "Orthopaedics" },
      { value: "URO", label: "Urology" },
      { value: "ENDO", label: "Endocrinology" },
    ]},
    { param: "status", label: "Status", options: [
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientAge", label: "Patient Age", type: "number" },
    { name: "patientSex", label: "Patient Sex", type: "select", options: [
      { value: "male", label: "Male" }, { value: "female", label: "Female" },
    ]},
    { name: "encounterId", label: "Encounter ID", type: "text" },
    { name: "departmentCode", label: "Specialty", type: "select", required: true, options: [
      { value: "DENTAL", label: "Dental" },
      { value: "OPHTH", label: "Ophthalmology" },
      { value: "ENT", label: "ENT" },
      { value: "PHYSIO", label: "Physiotherapy" },
      { value: "PSYCH", label: "Psychiatry" },
      { value: "DERM", label: "Dermatology" },
      { value: "CARDIO", label: "Cardiology" },
      { value: "NEURO", label: "Neurology" },
      { value: "ORTHO", label: "Orthopaedics" },
      { value: "URO", label: "Urology" },
      { value: "ENDO", label: "Endocrinology" },
    ]},
    { name: "clinicType", label: "Clinic Type", type: "select", options: [
      { value: "new", label: "New Visit" },
      { value: "follow_up", label: "Follow-up" },
      { value: "review", label: "Review" },
    ]},
    { name: "chiefComplaint", label: "Chief Complaint", type: "text", required: true, full: true },
    { name: "history", label: "History", type: "textarea", full: true },
    { name: "examination", label: "Examination", type: "textarea", full: true },
    { name: "diagnosis", label: "Diagnosis", type: "textarea", full: true },
    { name: "treatmentPlan", label: "Treatment Plan", type: "textarea", full: true },
    { name: "procedureDone", label: "Procedure Done", type: "textarea", full: true },
    { name: "prescription", label: "Prescription", type: "textarea", full: true },
    { name: "clinicianName", label: "Clinician", type: "text" },
    { name: "clinicianId", label: "Clinician ID", type: "text" },
    { name: "followUpDate", label: "Follow-up Date", type: "date" },
    { name: "nextAppointment", label: "Next Appointment", type: "datetime-local" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
    { name: "startTime", label: "Start Time", type: "datetime-local" },
    { name: "endTime", label: "End Time", type: "datetime-local" },
  ],
  auditActionCreate: "SPECIALTY_ENCOUNTER_CREATED",
  auditActionUpdate: "SPECIALTY_ENCOUNTER_UPDATED",
  accentColor: "text-purple-600",
};

// =====================================================================
// SUPPORT SERVICES (Laundry, Housekeeping, Catering, Waste, Security, Transport)
// =====================================================================
export const SUPPORT_SERVICES_CONFIG: ModuleConfig = {
  viewKey: "service_requests",
  title: "Support Services",
  description: "Laundry, Housekeeping, Catering, Waste Management, Security, and Transport/Ambulance requests.",
  icon: Sparkles,
  apiPath: "service-requests",
  queryKey: "service-requests",
  viewPermission: "support_services.view",
  managePermission: "support_services.manage",
  numberField: "requestNumber",
  searchFields: ["requestNumber", "title", "patientName", "location"],
  filters: [
    { param: "serviceType", label: "Service", options: [
      { value: "laundry", label: "Laundry" },
      { value: "housekeeping", label: "Housekeeping" },
      { value: "catering", label: "Catering" },
      { value: "waste", label: "Waste Mgmt" },
      { value: "security", label: "Security" },
      { value: "transport", label: "Transport" },
    ]},
    { param: "status", label: "Status", options: [
      { value: "requested", label: "Requested" },
      { value: "assigned", label: "Assigned" },
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
    { param: "priority", label: "Priority", options: PRIORITY_OPTIONS },
  ],
  fields: [
    { name: "serviceType", label: "Service Type", type: "select", required: true, options: [
      { value: "laundry", label: "Laundry" },
      { value: "housekeeping", label: "Housekeeping" },
      { value: "catering", label: "Catering" },
      { value: "waste", label: "Waste Management" },
      { value: "security", label: "Security" },
      { value: "transport", label: "Transport / Ambulance" },
    ]},
    { name: "title", label: "Title", type: "text", required: true, full: true },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "priority", label: "Priority", type: "select", options: PRIORITY_OPTIONS },
    { name: "status", label: "Status", type: "select", options: [
      { value: "requested", label: "Requested" },
      { value: "assigned", label: "Assigned" },
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
    { name: "category", label: "Sub-category", type: "text", placeholder: "e.g. linens, room_cleaning, patient_meal, sharp_disposal, visitor_pass, ambulance_trip" },
    { name: "location", label: "Location", type: "text", placeholder: "Ward / Room / Area" },
    { name: "departmentCode", label: "Department Code", type: "text" },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientName", label: "Patient Name", type: "text" },
    { name: "encounterId", label: "Encounter ID", type: "text" },
    { name: "admissionId", label: "Admission ID", type: "text" },
    { name: "assignedToName", label: "Assigned To", type: "text" },
    { name: "assignedToId", label: "Assigned To ID", type: "text" },
    { name: "requestedByName", label: "Requested By", type: "text" },
    { name: "requestedById", label: "Requested By ID", type: "text" },
    { name: "scheduledAt", label: "Scheduled At", type: "datetime-local" },
    { name: "startedAt", label: "Started At", type: "datetime-local" },
    { name: "completedAt", label: "Completed At", type: "datetime-local" },
    { name: "quantity", label: "Quantity", type: "number" },
    { name: "unit", label: "Unit", type: "text", placeholder: "pcs / kg / meal / bag / trip" },
    { name: "itemsDetail", label: "Items Detail (JSON)", type: "textarea", full: true },
    { name: "cost", label: "Cost", type: "number" },
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "SERVICE_REQUEST_CREATED",
  auditActionUpdate: "SERVICE_REQUEST_UPDATED",
  accentColor: "text-teal-600",
};

// =====================================================================
// PATIENT FEEDBACK / PATIENT RELATIONS
// =====================================================================
export const PATIENT_FEEDBACK_CONFIG: ModuleConfig = {
  viewKey: "patient_feedback",
  title: "Patient Relations",
  description: "Patient complaints, compliments, suggestions, enquiries. Track resolution.",
  icon: MessageSquare,
  apiPath: "patient-feedback",
  queryKey: "patient-feedback",
  viewPermission: "patient_relations.view",
  managePermission: "patient_relations.manage",
  numberField: "feedbackNumber",
  searchFields: ["feedbackNumber", "patientName", "subject", "description"],
  filters: [
    { param: "feedbackType", label: "Type", options: [
      { value: "complaint", label: "Complaint" },
      { value: "compliment", label: "Compliment" },
      { value: "suggestion", label: "Suggestion" },
      { value: "enquiry", label: "Enquiry" },
    ]},
    { param: "status", label: "Status", options: [
      { value: "open", label: "Open" },
      { value: "investigating", label: "Investigating" },
      { value: "resolved", label: "Resolved" },
      { value: "closed", label: "Closed" },
      { value: "escalated", label: "Escalated" },
    ]},
    { param: "severity", label: "Severity", options: SEVERITY_OPTIONS },
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientPhone", label: "Patient Phone", type: "text" },
    { name: "feedbackType", label: "Feedback Type", type: "select", required: true, options: [
      { value: "complaint", label: "Complaint" },
      { value: "compliment", label: "Compliment" },
      { value: "suggestion", label: "Suggestion" },
      { value: "enquiry", label: "Enquiry" },
    ]},
    { name: "category", label: "Category", type: "select", options: [
      { value: "clinical", label: "Clinical" },
      { value: "billing", label: "Billing" },
      { value: "waiting", label: "Waiting Times" },
      { value: "staff", label: "Staff Conduct" },
      { value: "cleanliness", label: "Cleanliness" },
      { value: "food", label: "Food" },
      { value: "other", label: "Other" },
    ]},
    { name: "departmentCode", label: "Department Code", type: "text" },
    { name: "subject", label: "Subject", type: "text", required: true, full: true },
    { name: "description", label: "Description", type: "textarea", required: true, full: true },
    { name: "severity", label: "Severity", type: "select", options: SEVERITY_OPTIONS },
    { name: "status", label: "Status", type: "select", options: [
      { value: "open", label: "Open" },
      { value: "investigating", label: "Investigating" },
      { value: "resolved", label: "Resolved" },
      { value: "closed", label: "Closed" },
      { value: "escalated", label: "Escalated" },
    ]},
    { name: "resolution", label: "Resolution", type: "textarea", full: true },
    { name: "resolvedByName", label: "Resolved By", type: "text" },
    { name: "resolvedById", label: "Resolved By ID", type: "text" },
    { name: "satisfactionScore", label: "Satisfaction Score (1-5)", type: "number" },
  ],
  auditActionCreate: "PATIENT_FEEDBACK_CREATED",
  auditActionUpdate: "PATIENT_FEEDBACK_UPDATED",
  accentColor: "text-blue-600",
};

// =====================================================================
// QUALITY INDICATORS
// =====================================================================
export const QUALITY_INDICATOR_CONFIG: ModuleConfig = {
  viewKey: "quality_indicators",
  title: "Quality Assurance",
  description: "Define and track quality indicators across clinical, safety, and operational domains.",
  icon: ClipboardCheck,
  apiPath: "quality-indicators",
  queryKey: "quality-indicators",
  viewPermission: "qa.view",
  managePermission: "qa.manage",
  numberField: "indicatorCode",
  searchFields: ["indicatorCode", "indicatorName", "category"],
  filters: [
    { param: "category", label: "Category", options: [
      { value: "clinical", label: "Clinical" },
      { value: "safety", label: "Safety" },
      { value: "patient_experience", label: "Patient Experience" },
      { value: "efficiency", label: "Efficiency" },
      { value: "financial", label: "Financial" },
    ]},
    { param: "isActive", label: "Active", options: [
      { value: "true", label: "Active" },
      { value: "false", label: "Inactive" },
    ]},
  ],
  fields: [
    { name: "indicatorName", label: "Indicator Name", type: "text", required: true },
    { name: "indicatorCode", label: "Indicator Code", type: "text", placeholder: "Auto-generated" },
    { name: "category", label: "Category", type: "select", options: [
      { value: "clinical", label: "Clinical" },
      { value: "safety", label: "Safety" },
      { value: "patient_experience", label: "Patient Experience" },
      { value: "efficiency", label: "Efficiency" },
      { value: "financial", label: "Financial" },
    ]},
    { name: "unit", label: "Unit", type: "text", placeholder: "% / rate / count" },
    { name: "target", label: "Target", type: "text" },
    { name: "measurementFrequency", label: "Frequency", type: "select", options: [
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
      { value: "monthly", label: "Monthly" },
      { value: "quarterly", label: "Quarterly" },
    ]},
    { name: "departmentCode", label: "Department Code", type: "text" },
    { name: "isActive", label: "Active", type: "checkbox" },
    { name: "description", label: "Description", type: "textarea", full: true },
  ],
  auditActionCreate: "QUALITY_INDICATOR_CREATED",
  auditActionUpdate: "QUALITY_INDICATOR_UPDATED",
  accentColor: "text-emerald-600",
};

// =====================================================================
// RISK REGISTER
// =====================================================================
export const RISK_REGISTER_CONFIG: ModuleConfig = {
  viewKey: "risk_register",
  title: "Risk Management",
  description: "Maintain a risk register, track mitigations, and review residual risks.",
  icon: AlertTriangle,
  apiPath: "risk-register",
  queryKey: "risk-register",
  viewPermission: "risk.view",
  managePermission: "risk.manage",
  numberField: "riskNumber",
  searchFields: ["riskNumber", "riskTitle", "description", "owner"],
  filters: [
    { param: "status", label: "Status", options: OPEN_CLOSED },
    { param: "riskCategory", label: "Category", options: [
      { value: "clinical", label: "Clinical" },
      { value: "financial", label: "Financial" },
      { value: "operational", label: "Operational" },
      { value: "strategic", label: "Strategic" },
      { value: "compliance", label: "Compliance" },
      { value: "reputational", label: "Reputational" },
    ]},
  ],
  fields: [
    { name: "riskTitle", label: "Risk Title", type: "text", required: true, full: true },
    { name: "riskCategory", label: "Category", type: "select", options: [
      { value: "clinical", label: "Clinical" },
      { value: "financial", label: "Financial" },
      { value: "operational", label: "Operational" },
      { value: "strategic", label: "Strategic" },
      { value: "compliance", label: "Compliance" },
      { value: "reputational", label: "Reputational" },
    ]},
    { name: "description", label: "Description", type: "textarea", required: true, full: true },
    { name: "likelihood", label: "Likelihood", type: "select", options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ]},
    { name: "impact", label: "Impact", type: "select", options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
      { value: "critical", label: "Critical" },
    ]},
    { name: "riskScore", label: "Risk Score", type: "text" },
    { name: "owner", label: "Risk Owner", type: "text" },
    { name: "ownerId", label: "Owner ID", type: "text" },
    { name: "mitigationPlan", label: "Mitigation Plan", type: "textarea", full: true },
    { name: "residualRisk", label: "Residual Risk", type: "text" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "open", label: "Open" },
      { value: "mitigated", label: "Mitigated" },
      { value: "accepted", label: "Accepted" },
      { value: "closed", label: "Closed" },
    ]},
    { name: "reviewDate", label: "Review Date", type: "date" },
    { name: "departmentCode", label: "Department Code", type: "text" },
    { name: "relatedIncidentId", label: "Related Incident ID", type: "text" },
  ],
  auditActionCreate: "RISK_REGISTER_CREATED",
  auditActionUpdate: "RISK_REGISTER_UPDATED",
  accentColor: "text-amber-600",
};

// =====================================================================
// LEGAL CASES
// =====================================================================
export const LEGAL_CASE_CONFIG: ModuleConfig = {
  viewKey: "legal_cases",
  title: "Legal & Compliance",
  description: "Track legal cases, regulatory matters, and compliance items.",
  icon: Scale,
  apiPath: "legal-cases",
  queryKey: "legal-cases",
  viewPermission: "legal.view",
  managePermission: "legal.manage",
  numberField: "caseNumber",
  searchFields: ["caseNumber", "title", "plaintiffName", "defendantName"],
  filters: [
    { param: "caseType", label: "Type", options: [
      { value: "malpractice", label: "Malpractice" },
      { value: "employment", label: "Employment" },
      { value: "contract", label: "Contract" },
      { value: "regulatory", label: "Regulatory" },
      { value: "patient_dispute", label: "Patient Dispute" },
      { value: "other", label: "Other" },
    ]},
    { param: "status", label: "Status", options: [
      { value: "open", label: "Open" },
      { value: "in_litigation", label: "In Litigation" },
      { value: "settled", label: "Settled" },
      { value: "dismissed", label: "Dismissed" },
      { value: "closed", label: "Closed" },
    ]},
  ],
  fields: [
    { name: "caseType", label: "Case Type", type: "select", required: true, options: [
      { value: "malpractice", label: "Malpractice" },
      { value: "employment", label: "Employment" },
      { value: "contract", label: "Contract" },
      { value: "regulatory", label: "Regulatory" },
      { value: "patient_dispute", label: "Patient Dispute" },
      { value: "other", label: "Other" },
    ]},
    { name: "title", label: "Case Title", type: "text", required: true, full: true },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "priority", label: "Priority", type: "select", options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ]},
    { name: "status", label: "Status", type: "select", options: [
      { value: "open", label: "Open" },
      { value: "in_litigation", label: "In Litigation" },
      { value: "settled", label: "Settled" },
      { value: "dismissed", label: "Dismissed" },
      { value: "closed", label: "Closed" },
    ]},
    { name: "filingDate", label: "Filing Date", type: "date" },
    { name: "courtDate", label: "Court Date", type: "datetime-local" },
    { name: "opposingParty", label: "Opposing Party", type: "text" },
    { name: "plaintiffName", label: "Plaintiff", type: "text" },
    { name: "defendantName", label: "Defendant", type: "text" },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientName", label: "Patient Name", type: "text" },
    { name: "encounterId", label: "Encounter ID", type: "text" },
    { name: "departmentCode", label: "Department Code", type: "text" },
    { name: "assignedAttorney", label: "Assigned Attorney", type: "text" },
    { name: "estimatedValue", label: "Estimated Value", type: "number" },
    { name: "settlementAmount", label: "Settlement Amount", type: "number" },
    { name: "resolutionNotes", label: "Resolution Notes", type: "textarea", full: true },
    { name: "closedAt", label: "Closed At", type: "datetime-local" },
  ],
  auditActionCreate: "LEGAL_CASE_CREATED",
  auditActionUpdate: "LEGAL_CASE_UPDATED",
  accentColor: "text-slate-700",
};

// =====================================================================
// RESEARCH STUDIES
// =====================================================================
export const RESEARCH_CONFIG: ModuleConfig = {
  viewKey: "research",
  title: "Research & Studies",
  description: "Manage research projects, ethics approvals, and participant enrollment.",
  icon: FlaskRound,
  apiPath: "research",
  queryKey: "research-studies",
  viewPermission: "research.view",
  managePermission: "research.manage",
  numberField: "studyNumber",
  searchFields: ["studyNumber", "studyTitle", "principalInvestigator"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "planning", label: "Planning" },
      { value: "recruiting", label: "Recruiting" },
      { value: "ongoing", label: "Ongoing" },
      { value: "analysis", label: "Analysis" },
      { value: "completed", label: "Completed" },
      { value: "suspended", label: "Suspended" },
      { value: "terminated", label: "Terminated" },
    ]},
  ],
  fields: [
    { name: "studyTitle", label: "Study Title", type: "text", required: true, full: true },
    { name: "studyType", label: "Study Type", type: "select", options: [
      { value: "observational", label: "Observational" },
      { value: "rct", label: "RCT" },
      { value: "cohort", label: "Cohort" },
      { value: "case_control", label: "Case-Control" },
      { value: "qualitative", label: "Qualitative" },
    ]},
    { name: "principalInvestigator", label: "Principal Investigator", type: "text" },
    { name: "principalInvestigatorId", label: "PI ID", type: "text" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "planning", label: "Planning" },
      { value: "recruiting", label: "Recruiting" },
      { value: "ongoing", label: "Ongoing" },
      { value: "analysis", label: "Analysis" },
      { value: "completed", label: "Completed" },
      { value: "suspended", label: "Suspended" },
      { value: "terminated", label: "Terminated" },
    ]},
    { name: "ethicsApprovalNo", label: "Ethics Approval #", type: "text" },
    { name: "ethicsApprovalDate", label: "Ethics Approval Date", type: "date" },
    { name: "startDate", label: "Start Date", type: "date" },
    { name: "endDate", label: "End Date", type: "date" },
    { name: "targetEnrollment", label: "Target Enrollment", type: "number" },
    { name: "currentEnrollment", label: "Current Enrollment", type: "number" },
    { name: "fundingSource", label: "Funding Source", type: "text" },
    { name: "budget", label: "Budget", type: "number" },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "RESEARCH_STUDY_CREATED",
  auditActionUpdate: "RESEARCH_STUDY_UPDATED",
  accentColor: "text-purple-600",
};

// =====================================================================
// PR ACTIVITIES
// =====================================================================
export const PR_CONFIG: ModuleConfig = {
  viewKey: "pr_activities",
  title: "Public Relations",
  description: "PR campaigns, media inquiries, press releases, and community engagement events.",
  icon: Megaphone,
  apiPath: "pr-activities",
  queryKey: "pr-activities",
  viewPermission: "pr.view",
  managePermission: "pr.manage",
  numberField: "activityNumber",
  searchFields: ["activityNumber", "title", "mediaOutlet", "contactPerson"],
  filters: [
    { param: "activityType", label: "Type", options: [
      { value: "campaign", label: "Campaign" },
      { value: "media_inquiry", label: "Media Inquiry" },
      { value: "press_release", label: "Press Release" },
      { value: "event", label: "Event" },
      { value: "social_media", label: "Social Media" },
      { value: "community_engagement", label: "Community Engagement" },
    ]},
    { param: "status", label: "Status", options: [
      { value: "planned", label: "Planned" },
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
  ],
  fields: [
    { name: "activityType", label: "Activity Type", type: "select", required: true, options: [
      { value: "campaign", label: "Campaign" },
      { value: "media_inquiry", label: "Media Inquiry" },
      { value: "press_release", label: "Press Release" },
      { value: "event", label: "Event" },
      { value: "social_media", label: "Social Media" },
      { value: "community_engagement", label: "Community Engagement" },
    ]},
    { name: "title", label: "Title", type: "text", required: true, full: true },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "status", label: "Status", type: "select", options: [
      { value: "planned", label: "Planned" },
      { value: "in_progress", label: "In Progress" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
    { name: "priority", label: "Priority", type: "select", options: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ]},
    { name: "startDate", label: "Start Date", type: "datetime-local" },
    { name: "endDate", label: "End Date", type: "datetime-local" },
    { name: "targetAudience", label: "Target Audience", type: "text" },
    { name: "budget", label: "Budget", type: "number" },
    { name: "spentAmount", label: "Spent Amount", type: "number" },
    { name: "mediaOutlet", label: "Media Outlet", type: "text" },
    { name: "contactPerson", label: "Contact Person", type: "text" },
    { name: "contactPhone", label: "Contact Phone", type: "text" },
    { name: "outcomes", label: "Outcomes", type: "textarea", full: true },
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "PR_ACTIVITY_CREATED",
  auditActionUpdate: "PR_ACTIVITY_UPDATED",
  accentColor: "text-pink-600",
};

// =====================================================================
// IT TICKETS
// =====================================================================
export const IT_TICKET_CONFIG: ModuleConfig = {
  viewKey: "it_tickets",
  title: "IT Support",
  description: "Manage IT support tickets for hardware, software, network, and access issues.",
  icon: Server,
  apiPath: "it-tickets",
  queryKey: "it-tickets",
  viewPermission: "it.view",
  managePermission: "it.manage",
  numberField: "ticketNumber",
  searchFields: ["ticketNumber", "subject", "description", "affectedSystem", "reportedByName"],
  filters: [
    { param: "ticketType", label: "Type", options: [
      { value: "hardware", label: "Hardware" },
      { value: "software", label: "Software" },
      { value: "network", label: "Network" },
      { value: "access", label: "Access" },
      { value: "email", label: "Email" },
      { value: "other", label: "Other" },
    ]},
    { param: "status", label: "Status", options: [
      { value: "open", label: "Open" },
      { value: "assigned", label: "Assigned" },
      { value: "in_progress", label: "In Progress" },
      { value: "resolved", label: "Resolved" },
      { value: "closed", label: "Closed" },
      { value: "escalated", label: "Escalated" },
    ]},
    { param: "priority", label: "Priority", options: SEVERITY_OPTIONS },
  ],
  fields: [
    { name: "ticketType", label: "Ticket Type", type: "select", required: true, options: [
      { value: "hardware", label: "Hardware" },
      { value: "software", label: "Software" },
      { value: "network", label: "Network" },
      { value: "access", label: "Access" },
      { value: "email", label: "Email" },
      { value: "other", label: "Other" },
    ]},
    { name: "category", label: "Category", type: "text" },
    { name: "subject", label: "Subject", type: "text", required: true, full: true },
    { name: "description", label: "Description", type: "textarea", required: true, full: true },
    { name: "affectedSystem", label: "Affected System", type: "text" },
    { name: "priority", label: "Priority", type: "select", options: SEVERITY_OPTIONS },
    { name: "status", label: "Status", type: "select", options: [
      { value: "open", label: "Open" },
      { value: "assigned", label: "Assigned" },
      { value: "in_progress", label: "In Progress" },
      { value: "resolved", label: "Resolved" },
      { value: "closed", label: "Closed" },
      { value: "escalated", label: "Escalated" },
    ]},
    { name: "reportedByName", label: "Reported By", type: "text" },
    { name: "reportedById", label: "Reported By ID", type: "text" },
    { name: "reportedByPhone", label: "Reporter Phone", type: "text" },
    { name: "assignedToName", label: "Assigned To", type: "text" },
    { name: "assignedToId", label: "Assigned To ID", type: "text" },
    { name: "resolution", label: "Resolution", type: "textarea", full: true },
    { name: "resolvedAt", label: "Resolved At", type: "datetime-local" },
    { name: "resolutionTimeMins", label: "Resolution Time (mins)", type: "number" },
    { name: "satisfactionScore", label: "Satisfaction (1-5)", type: "number" },
  ],
  auditActionCreate: "IT_TICKET_CREATED",
  auditActionUpdate: "IT_TICKET_UPDATED",
  accentColor: "text-indigo-600",
};

// =====================================================================
// CODING RECORDS
// =====================================================================
export const CODING_RECORD_CONFIG: ModuleConfig = {
  viewKey: "coding_records",
  title: "Coding & Claims",
  description: "ICD-10/11 coding for encounters and insurance claim preparation.",
  icon: FileText,
  apiPath: "coding-records",
  queryKey: "coding-records",
  viewPermission: "coding.view",
  managePermission: "coding.manage",
  searchFields: ["patientName", "primaryCode", "primaryDescription"],
  filters: [
    { param: "codingType", label: "Type", options: [
      { value: "icd10", label: "ICD-10" },
      { value: "icd11", label: "ICD-11" },
      { value: "cpt", label: "CPT" },
      { value: "snomed", label: "SNOMED" },
    ]},
    { param: "claimStatus", label: "Claim Status", options: [
      { value: "pending", label: "Pending" },
      { value: "submitted", label: "Submitted" },
      { value: "approved", label: "Approved" },
      { value: "rejected", label: "Rejected" },
      { value: "paid", label: "Paid" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "encounterId", label: "Encounter ID", type: "text" },
    { name: "codingType", label: "Coding System", type: "select", options: [
      { value: "icd10", label: "ICD-10" },
      { value: "icd11", label: "ICD-11" },
      { value: "cpt", label: "CPT" },
      { value: "snomed", label: "SNOMED" },
    ]},
    { name: "primaryCode", label: "Primary Code", type: "text", required: true },
    { name: "primaryDescription", label: "Primary Description", type: "text", required: true, full: true },
    { name: "secondaryCodes", label: "Secondary Codes (JSON array)", type: "textarea", full: true },
    { name: "coderName", label: "Coder", type: "text" },
    { name: "coderId", label: "Coder ID", type: "text" },
    { name: "claimId", label: "Claim ID", type: "text" },
    { name: "claimStatus", label: "Claim Status", type: "select", options: [
      { value: "pending", label: "Pending" },
      { value: "submitted", label: "Submitted" },
      { value: "approved", label: "Approved" },
      { value: "rejected", label: "Rejected" },
      { value: "paid", label: "Paid" },
    ]},
    { name: "claimAmount", label: "Claim Amount", type: "number" },
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "CODING_RECORD_CREATED",
  auditActionUpdate: "CODING_RECORD_UPDATED",
  accentColor: "text-cyan-600",
};

// =====================================================================
// COMMUNITY OUTREACH
// =====================================================================
export const COMMUNITY_OUTREACH_CONFIG: ModuleConfig = {
  viewKey: "community_outreach",
  title: "Community Health",
  description: "Plan and track community outreach, vaccination drives, screenings, and health education.",
  icon: Users,
  apiPath: "community-outreach",
  queryKey: "community-outreach",
  viewPermission: "community_health.view",
  managePermission: "community_health.manage",
  numberField: "eventNumber",
  searchFields: ["eventNumber", "title", "location", "teamLeadName"],
  filters: [
    { param: "eventType", label: "Type", options: [
      { value: "vaccination", label: "Vaccination" },
      { value: "screening", label: "Screening" },
      { value: "health_education", label: "Health Education" },
      { value: "community_clinic", label: "Community Clinic" },
      { value: "sanitation", label: "Sanitation" },
    ]},
    { param: "status", label: "Status", options: [
      { value: "planned", label: "Planned" },
      { value: "ongoing", label: "Ongoing" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
  ],
  fields: [
    { name: "eventType", label: "Event Type", type: "select", required: true, options: [
      { value: "vaccination", label: "Vaccination" },
      { value: "screening", label: "Screening" },
      { value: "health_education", label: "Health Education" },
      { value: "community_clinic", label: "Community Clinic" },
      { value: "sanitation", label: "Sanitation" },
    ]},
    { name: "title", label: "Event Title", type: "text", required: true, full: true },
    { name: "description", label: "Description", type: "textarea", full: true },
    { name: "location", label: "Location", type: "text", required: true },
    { name: "region", label: "Region", type: "text" },
    { name: "startDate", label: "Start Date", type: "datetime-local", required: true },
    { name: "endDate", label: "End Date", type: "datetime-local" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "planned", label: "Planned" },
      { value: "ongoing", label: "Ongoing" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ]},
    { name: "targetPopulation", label: "Target Population", type: "number" },
    { name: "participantsReached", label: "Participants Reached", type: "number" },
    { name: "servicesProvided", label: "Services Provided (JSON)", type: "textarea", full: true },
    { name: "teamLeadName", label: "Team Lead", type: "text" },
    { name: "teamLeadId", label: "Team Lead ID", type: "text" },
    { name: "teamMembers", label: "Team Members", type: "textarea", full: true },
    { name: "budget", label: "Budget", type: "number" },
    { name: "spentAmount", label: "Spent Amount", type: "number" },
    { name: "outcomes", label: "Outcomes", type: "textarea", full: true },
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "COMMUNITY_OUTREACH_CREATED",
  auditActionUpdate: "COMMUNITY_OUTREACH_UPDATED",
  accentColor: "text-emerald-600",
};

// =====================================================================
// HOME CARE VISITS
// =====================================================================
export const HOME_CARE_CONFIG: ModuleConfig = {
  viewKey: "home_care",
  title: "Home Care Services",
  description: "Schedule and document home care visits for nursing, physiotherapy, palliative, and postnatal care.",
  icon: Home,
  apiPath: "home-care",
  queryKey: "home-care",
  viewPermission: "home_care.view",
  managePermission: "home_care.manage",
  numberField: "visitNumber",
  searchFields: ["visitNumber", "patientName", "patientAddress"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "scheduled", label: "Scheduled" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
      { value: "no_show", label: "No Show" },
    ]},
    { param: "visitType", label: "Type", options: [
      { value: "nursing", label: "Nursing" },
      { value: "physiotherapy", label: "Physiotherapy" },
      { value: "medical_review", label: "Medical Review" },
      { value: "palliative", label: "Palliative" },
      { value: "postnatal", label: "Postnatal" },
      { value: "chronic_disease", label: "Chronic Disease" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientAge", label: "Patient Age", type: "number" },
    { name: "patientSex", label: "Patient Sex", type: "select", options: [
      { value: "male", label: "Male" }, { value: "female", label: "Female" },
    ]},
    { name: "patientAddress", label: "Patient Address", type: "textarea", required: true, full: true },
    { name: "patientPhone", label: "Patient Phone", type: "text" },
    { name: "visitType", label: "Visit Type", type: "select", required: true, options: [
      { value: "nursing", label: "Nursing" },
      { value: "physiotherapy", label: "Physiotherapy" },
      { value: "medical_review", label: "Medical Review" },
      { value: "palliative", label: "Palliative" },
      { value: "postnatal", label: "Postnatal" },
      { value: "chronic_disease", label: "Chronic Disease" },
    ]},
    { name: "scheduledAt", label: "Scheduled At", type: "datetime-local", required: true },
    { name: "arrivedAt", label: "Arrived At", type: "datetime-local" },
    { name: "departedAt", label: "Departed At", type: "datetime-local" },
    { name: "durationMins", label: "Duration (mins)", type: "number" },
    { name: "caregiverName", label: "Caregiver", type: "text" },
    { name: "caregiverId", label: "Caregiver ID", type: "text" },
    { name: "careProvided", label: "Care Provided", type: "textarea", full: true },
    { name: "vitalsRecorded", label: "Vitals (JSON)", type: "textarea", full: true },
    { name: "medicationsGiven", label: "Medications Given", type: "textarea", full: true },
    { name: "instructions", label: "Instructions", type: "textarea", full: true },
    { name: "nextVisitDate", label: "Next Visit Date", type: "datetime-local" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "scheduled", label: "Scheduled" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
      { value: "no_show", label: "No Show" },
    ]},
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "HOME_CARE_VISIT_CREATED",
  auditActionUpdate: "HOME_CARE_VISIT_UPDATED",
  accentColor: "text-amber-600",
};

// =====================================================================
// HISTOPATHOLOGY
// =====================================================================
export const HISTOPATHOLOGY_CONFIG: ModuleConfig = {
  viewKey: "histopathology",
  title: "Histopathology",
  description: "Track specimens, gross examination, microscopy findings, and final diagnosis.",
  icon: Microscope,
  apiPath: "histopathology",
  queryKey: "histopathology",
  viewPermission: "histopathology.view",
  managePermission: "histopathology.manage",
  numberField: "specimenNumber",
  searchFields: ["specimenNumber", "patientName", "specimenSite", "diagnosis"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "received", label: "Received" },
      { value: "processing", label: "Processing" },
      { value: "sectioned", label: "Sectioned" },
      { value: "reported", label: "Reported" },
      { value: "signed_out", label: "Signed Out" },
    ]},
    { param: "specimenType", label: "Specimen", options: [
      { value: "biopsy", label: "Biopsy" },
      { value: "cytology", label: "Cytology" },
      { value: "resection", label: "Resection" },
      { value: "fluid", label: "Fluid" },
      { value: "tissue", label: "Tissue" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "patientAge", label: "Patient Age", type: "number" },
    { name: "patientSex", label: "Patient Sex", type: "select", options: [
      { value: "male", label: "Male" }, { value: "female", label: "Female" },
    ]},
    { name: "encounterId", label: "Encounter ID", type: "text" },
    { name: "specimenType", label: "Specimen Type", type: "select", required: true, options: [
      { value: "biopsy", label: "Biopsy" },
      { value: "cytology", label: "Cytology" },
      { value: "resection", label: "Resection" },
      { value: "fluid", label: "Fluid" },
      { value: "tissue", label: "Tissue" },
    ]},
    { name: "specimenSite", label: "Specimen Site", type: "text", required: true, full: true },
    { name: "collectionMethod", label: "Collection Method", type: "select", options: [
      { value: "excisional", label: "Excisional" },
      { value: "incisional", label: "Incisional" },
      { value: "needle", label: "Needle" },
      { value: "brush", label: "Brush" },
      { value: "scraping", label: "Scraping" },
    ]},
    { name: "collectedAt", label: "Collected At", type: "datetime-local" },
    { name: "fixedIn", label: "Fixed In", type: "text", placeholder: "formalin" },
    { name: "clinicalHistory", label: "Clinical History", type: "textarea", full: true },
    { name: "requestingPhysicianName", label: "Requesting Physician", type: "text" },
    { name: "requestingPhysicianId", label: "Requesting Physician ID", type: "text" },
    { name: "grossExamination", label: "Gross Examination", type: "textarea", full: true },
    { name: "microscopyFindings", label: "Microscopy Findings", type: "textarea", full: true },
    { name: "diagnosis", label: "Diagnosis", type: "textarea", full: true },
    { name: "differentialDiagnosis", label: "Differential Diagnosis", type: "textarea", full: true },
    { name: "specialStains", label: "Special Stains", type: "text" },
    { name: "tumorType", label: "Tumor Type", type: "text" },
    { name: "tumorGrade", label: "Tumor Grade", type: "text" },
    { name: "tumorStage", label: "Tumor Stage", type: "text" },
    { name: "marginsStatus", label: "Margins Status", type: "text" },
    { name: "pathologistName", label: "Pathologist", type: "text" },
    { name: "pathologistId", label: "Pathologist ID", type: "text" },
    { name: "reportedAt", label: "Reported At", type: "datetime-local" },
    { name: "status", label: "Status", type: "select", options: [
      { value: "received", label: "Received" },
      { value: "processing", label: "Processing" },
      { value: "sectioned", label: "Sectioned" },
      { value: "reported", label: "Reported" },
      { value: "signed_out", label: "Signed Out" },
    ]},
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "HISTOPATHOLOGY_SPECIMEN_CREATED",
  auditActionUpdate: "HISTOPATHOLOGY_SPECIMEN_UPDATED",
  accentColor: "text-violet-600",
};

// =====================================================================
// RECOVERY ROOM
// =====================================================================
export const RECOVERY_ROOM_CONFIG: ModuleConfig = {
  viewKey: "recovery_room",
  title: "Recovery Room",
  description: "Track post-anesthesia recovery of patients after surgery.",
  icon: BedDouble,
  apiPath: "recovery-room",
  queryKey: "recovery-room",
  viewPermission: "recovery.view",
  managePermission: "recovery.manage",
  numberField: "recordNumber",
  searchFields: ["recordNumber", "patientName", "theatreCaseNumber"],
  filters: [
    { param: "status", label: "Status", options: [
      { value: "recovering", label: "Recovering" },
      { value: "recovered", label: "Recovered" },
      { value: "transferred", label: "Transferred" },
      { value: "complication", label: "Complication" },
    ]},
  ],
  fields: [
    { name: "patientName", label: "Patient Name", type: "text", required: true },
    { name: "patientId", label: "Patient ID", type: "text" },
    { name: "theatreCaseId", label: "Theatre Case ID", type: "text" },
    { name: "theatreCaseNumber", label: "Theatre Case Number", type: "text" },
    { name: "admissionId", label: "Admission ID", type: "text" },
    { name: "aldergroveScore", label: "Aldergrove Score (0-10)", type: "number" },
    { name: "painScore", label: "Pain Score (0-10)", type: "number" },
    { name: "vitals", label: "Vitals (JSON)", type: "textarea", full: true },
    { name: "complications", label: "Complications", type: "textarea", full: true },
    { name: "treatmentGiven", label: "Treatment Given", type: "textarea", full: true },
    { name: "destination", label: "Destination", type: "select", options: [
      { value: "ward", label: "Ward" },
      { value: "icu", label: "ICU" },
      { value: "home", label: "Home" },
      { value: "theatre_return", label: "Return to Theatre" },
    ]},
    { name: "status", label: "Status", type: "select", options: [
      { value: "recovering", label: "Recovering" },
      { value: "recovered", label: "Recovered" },
      { value: "transferred", label: "Transferred" },
      { value: "complication", label: "Complication" },
    ]},
    { name: "nurseName", label: "Nurse", type: "text" },
    { name: "nurseId", label: "Nurse ID", type: "text" },
    { name: "admittedAt", label: "Admitted At", type: "datetime-local" },
    { name: "dischargedAt", label: "Discharged At", type: "datetime-local" },
    { name: "notes", label: "Notes", type: "textarea", full: true },
  ],
  auditActionCreate: "RECOVERY_RECORD_CREATED",
  auditActionUpdate: "RECOVERY_RECORD_UPDATED",
  accentColor: "text-cyan-600",
};

// =====================================================================
// AUDIT FINDINGS (Internal Audit)
// =====================================================================
export const AUDIT_FINDING_CONFIG: ModuleConfig = {
  viewKey: "audit_findings",
  title: "Internal Audit",
  description: "Track audit findings across financial, operational, clinical, and IT domains.",
  icon: ScrollText,
  apiPath: "audit-findings",
  queryKey: "audit-findings",
  viewPermission: "audit.view",
  managePermission: "audit.manage",
  numberField: "findingNumber",
  searchFields: ["findingNumber", "title", "description", "auditorName"],
  filters: [
    { param: "auditType", label: "Type", options: [
      { value: "financial", label: "Financial" },
      { value: "operational", label: "Operational" },
      { value: "compliance", label: "Compliance" },
      { value: "clinical", label: "Clinical" },
      { value: "it", label: "IT" },
    ]},
    { param: "status", label: "Status", options: OPEN_CLOSED },
    { param: "severity", label: "Severity", options: SEVERITY_OPTIONS },
  ],
  fields: [
    { name: "auditType", label: "Audit Type", type: "select", required: true, options: [
      { value: "financial", label: "Financial" },
      { value: "operational", label: "Operational" },
      { value: "compliance", label: "Compliance" },
      { value: "clinical", label: "Clinical" },
      { value: "it", label: "IT" },
    ]},
    { name: "title", label: "Finding Title", type: "text", required: true, full: true },
    { name: "description", label: "Description", type: "textarea", required: true, full: true },
    { name: "findingType", label: "Finding Type", type: "select", options: [
      { value: "observation", label: "Observation" },
      { value: "weakness", label: "Weakness" },
      { value: "non_conformance", label: "Non-Conformance" },
      { value: "fraud", label: "Fraud" },
    ]},
    { name: "severity", label: "Severity", type: "select", options: SEVERITY_OPTIONS },
    { name: "status", label: "Status", type: "select", options: [
      { value: "open", label: "Open" },
      { value: "in_review", label: "In Review" },
      { value: "remediated", label: "Remediated" },
      { value: "closed", label: "Closed" },
    ]},
    { name: "auditorName", label: "Auditor", type: "text" },
    { name: "auditorId", label: "Auditor ID", type: "text" },
    { name: "auditedPeriod", label: "Audited Period", type: "text" },
    { name: "auditedDepartment", label: "Audited Department", type: "text" },
    { name: "recommendation", label: "Recommendation", type: "textarea", full: true },
    { name: "managementResponse", label: "Management Response", type: "textarea", full: true },
    { name: "remediationPlan", label: "Remediation Plan", type: "textarea", full: true },
    { name: "remediationDueDate", label: "Remediation Due Date", type: "date" },
    { name: "remediatedAt", label: "Remediated At", type: "datetime-local" },
  ],
  auditActionCreate: "AUDIT_FINDING_CREATED",
  auditActionUpdate: "AUDIT_FINDING_UPDATED",
  accentColor: "text-slate-700",
};

// Export all configs as a map
export const MODULE_CONFIGS: Record<string, ModuleConfig> = {
  blood_donors: BLOOD_DONOR_CONFIG,
  blood_units: BLOOD_UNIT_CONFIG,
  blood_transfusions: BLOOD_TRANSFUSION_CONFIG,
  theatre: THEATRE_CONFIG,
  critical_care: CRITICAL_CARE_CONFIG,
  specialty: SPECIALTY_CONFIG,
  service_requests: SUPPORT_SERVICES_CONFIG,
  patient_feedback: PATIENT_FEEDBACK_CONFIG,
  quality_indicators: QUALITY_INDICATOR_CONFIG,
  risk_register: RISK_REGISTER_CONFIG,
  legal_cases: LEGAL_CASE_CONFIG,
  research: RESEARCH_CONFIG,
  pr_activities: PR_CONFIG,
  it_tickets: IT_TICKET_CONFIG,
  coding_records: CODING_RECORD_CONFIG,
  community_outreach: COMMUNITY_OUTREACH_CONFIG,
  home_care: HOME_CARE_CONFIG,
  histopathology: HISTOPATHOLOGY_CONFIG,
  recovery_room: RECOVERY_ROOM_CONFIG,
  audit_findings: AUDIT_FINDING_CONFIG,
};
